#!/bin/bash

#   Autor: Jagoda Rybacka
#   Zadanie 4
#   Program, który wypompowuje "ładny" tekst z Wikipedii na określony temat.
# - Możliwe tematy to kategorie wikipedii.
# - Program umożliwia przeglądanie drzewa kategorii.
# - Wypompowuje tekst ze stron należących do zadanej kategorii i wszystkich jej podkategorii.
#
#  Instrukcja obsługi: plik README.md

var=$1
if [[ $1 = '-i' ]]; then
  var=$2
fi
rm -rf ./wiki
node ./scrapeText.js $var
echo 'Scrapping done'
node ./extractText.js
echo 'Extracting done'
find ./wiki -name '*.html' -type f -delete
node ./parseText.js
echo 'Parsing done'
if [[ $1 = '-i' ]]; then
  node ./cli.js
fi
